from celula.States import States as s
initial_state_GameOfLife = [
    [{'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}],
    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],
    [{'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],
    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],
    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],

    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],
    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],
    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],
    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}, {'state': s.Vivo, 'tiempo_vivo':1, 'tiempo_muerto':0}],
    [{'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1},  {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}, {'state': s.Muerto, 'tiempo_vivo':0, 'tiempo_muerto':1}],

]



initial_state_GameOfLifeSimple = [
    [s.Vivo, s.Muerto, s.Muerto, s.Vivo, s.Muerto,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Vivo],
    [s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Vivo,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],
    [s.Vivo, s.Muerto, s.Muerto, s.Muerto, s.Vivo,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],
    [s.Muerto, s.Vivo, s.Vivo, s.Vivo, s.Vivo,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],
    [s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],

    [s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],
    [s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],
    [s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],
    [s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto,  s.Muerto, s.Muerto, s.Vivo, s.Vivo, s.Vivo],
    [s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto,  s.Muerto, s.Muerto, s.Muerto, s.Muerto, s.Muerto],

]